language: python
python:
  - "3.6"
# command to install dependencies
install:
  - sudo apt-get install libqt4-dev
  - pip install PySide2;
  # Travis CI servers use virtualenvs, so we need to finish the install by the following
  - pip install -e .
  - pip install -r test-requirements.txt
# command to run tests
script: pytest polibeepsync
